### PR TITLE
Increase and decrease volume using scrollwheel

### LINKED ISSUE #312: [Feat] Mousewheel to increase and decrease volume
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Ability to increase and decrease the volume with the mouse wheel.

### PR DESCRIPTION
**Pull request by pypp**
Add the ability to increase and decrease the volume using the mouse wheel.
resolves #312

### CODE REVIEW

**Comment by prayag17** [comment]
Thanks for your work but I will hold PRs for now

**Comment by pypp** [comment]
no problem.

**Comment by prayag17** [comment]
You can now fix the merge commit

**Comment by pypp** [comment]
I get the following error when trying to connect to server 
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by prayag17** [comment]
Ig that issue is cause by `useApiInContext` I have used as the api context in tanstack router would update instantly like it should have. I will take a look at it

**Comment by prayag17** [comment]
Hey @pypp, you can now rebase you PR. I will merge them as soon as you rebase

**Comment by pypp** [comment]
rebased.

**Review by prayag17 — APPROVED** [review]

**Comment by prayag17** [comment]
Thanks @pypp

**Pull request merged**
