### PR TITLE
 Double click to toggle fullscreen, single click to toggle playing

### LINKED ISSUE #309: [Feat] Double Click to enter and leave fullscreen
**Is your feature request related to a problem? Please describe.**
Can't double click on the canvas to get in full screen view, just like the web ui.

**Describe the solution you'd like**
Ability to double click on the canvas and get in the full screen view. 

**Describe alternatives you've considered**
Pressing the 'F' key, but my hand is not always by the keyboard.

### PR DESCRIPTION
**Pull request by pypp**
Added the option to toggle fullscreen and playing on video click.
resolves #309

### CODE REVIEW

**Comment by pypp** [comment]
The timeout might be too high, might want to lower it so that the player will feel more responsive.

**Comment by prayag17** [comment]
Hey @pypp, you can now rebase you PR. I will merge them as soon as you rebase

**Comment by pypp** [comment]
rebased, you can check it.

**Review by prayag17 — APPROVED** [review]

**Comment by prayag17** [comment]
Thanks @pypp

**Pull request merged**
